import json
import urllib.error
import urllib.request
from collections.abc import Callable
from typing import Any
from urllib.parse import urlparse

from app.core.config import Settings, get_settings
from app.models.imperium import ImperiumWeeklyReviewSession
from app.schemas.ai import QwenRoutingDecision, QwenScoreBreakdown, QwenWeeklySummary
from app.services.ai.roles import LOCAL_EXECUTOR_ROLE, resolve_model_id


class QwenProviderError(RuntimeError):
    pass


HttpPost = Callable[[str, dict[str, Any], int], dict[str, Any]]


class QwenClient:
    def __init__(
        self,
        *,
        settings: Settings | None = None,
        http_post: HttpPost | None = None,
    ) -> None:
        self.settings = settings or get_settings()
        self._http_post = http_post or self._post_json
        self._model_id: str | None = None

    @property
    def model_id(self) -> str:
        # Resolved through the local_executor role (ai_role_models), never hard-coded.
        if self._model_id is None:
            self._model_id = resolve_model_id(LOCAL_EXECUTOR_ROLE)
        return self._model_id

    def build_prompt(self, *, task_type: str, input_payload: dict, mode: str) -> str:
        return (
            "You are the local executor model inside Imperium. "
            "Return strict JSON only. Do not create canonical actions. "
            f"mode={mode}; task_type={task_type}; "
            f"input_payload={json.dumps(input_payload, sort_keys=True, default=str)}"
        )

    def classify_task(self, *, task_type: str, input_payload: dict) -> QwenRoutingDecision:
        if self._should_dry_run():
            return self._dry_run_routing_decision(task_type=task_type, input_payload=input_payload)
        raw = self.call(
            prompt=self.build_prompt(task_type=task_type, input_payload=input_payload, mode="route"),
            mode="route",
        )
        return QwenRoutingDecision.model_validate(raw)

    def score_task(self, *, task_type: str, input_payload: dict) -> int:
        return self.classify_task(task_type=task_type, input_payload=input_payload).difficulty_score

    def prepare_prompt_for_strong_model(self, *, task_type: str, input_payload: dict) -> dict[str, Any]:
        decision = self.classify_task(task_type=task_type, input_payload=input_payload)
        return {
            "task_type": task_type,
            "recommended_model": decision.recommended_model,
            "difficulty_score": decision.difficulty_score,
            "requires_user_validation": decision.requires_user_validation,
            "risk_flags": decision.risk_flags,
            "prepared_prompt": self.build_prompt(
                task_type=task_type,
                input_payload=input_payload,
                mode="strong_model_preparation",
            ),
        }

    def generate_weekly_summary(self, *, input_payload: dict) -> QwenWeeklySummary:
        if self._should_dry_run():
            return QwenWeeklySummary(
                result_type="weekly_report.summary",
                summary="Dry-run Qwen weekly summary. No model call was made.",
                sections=[
                    {
                        "title": "Dry-run summary",
                        "content": (
                            "This structured summary is generated by the backend Qwen adapter "
                            "to test the contract only."
                        ),
                    }
                ],
                questions=[
                    "What was the most important signal from this week?",
                    "What blocked execution the most?",
                    "What should change next week?",
                ],
                confidence=0.7,
                warnings=["dry_run_no_network", "proposal_only_not_canonical"],
            )
        raw = self.call(
            prompt=self.build_prompt(
                task_type="weekly_report.summary",
                input_payload=input_payload,
                mode="weekly_summary",
            ),
            mode="weekly_summary",
        )
        return QwenWeeklySummary.model_validate(raw)

    def call(self, *, prompt: str, mode: str) -> dict[str, Any]:
        if self._should_dry_run():
            if mode == "weekly_summary":
                return self.generate_weekly_summary(input_payload={"prompt": prompt}).model_dump(mode="json")
            return self._dry_run_routing_decision(task_type="unknown", input_payload={"prompt": prompt}).model_dump(
                mode="json"
            )
        if not self.settings.qwen_base_url:
            raise QwenProviderError("QWEN_BASE_URL is required when Qwen dry-run is disabled.")

        url = self.settings.qwen_base_url.rstrip("/") + "/api/generate"
        try:
            response = self._http_post(
                url,
                {
                    "model": self.model_id,
                    "prompt": prompt,
                    "stream": False,
                    "format": "json",
                },
                self.settings.qwen_request_timeout_seconds,
            )
        except Exception as exc:
            raise QwenProviderError("Qwen provider call failed.") from exc

        model_text = response.get("response", response)
        if isinstance(model_text, str):
            try:
                parsed = json.loads(model_text)
            except json.JSONDecodeError as exc:
                raise QwenProviderError("Qwen returned invalid JSON.") from exc
            if not isinstance(parsed, dict):
                raise QwenProviderError("Qwen returned JSON that is not an object.")
            return parsed
        if isinstance(model_text, dict):
            return model_text
        raise QwenProviderError("Qwen returned an unsupported response shape.")

    def _should_dry_run(self) -> bool:
        return self.settings.qwen_dry_run or not self.settings.qwen_enabled

    def _dry_run_routing_decision(self, *, task_type: str, input_payload: dict) -> QwenRoutingDecision:
        serialized_size = len(json.dumps(input_payload, sort_keys=True, default=str))
        context_size = min(10, serialized_size // 250)
        complexity = 6 if task_type.startswith("weekly_report.") else 3
        ambiguity = 4 if not input_payload else 2
        error_consequence = 6 if task_type.startswith(("vault.", "pulse.", "weekly_report.")) else 3
        speed_tolerance = 7 if task_type.startswith("weekly_report.") else 3
        data_sensitivity = 5 if task_type.startswith(("vault.", "pulse.", "weekly_report.")) else 3
        cost_justification = 4 if task_type.startswith("weekly_report.") else 1
        breakdown = QwenScoreBreakdown(
            complexity=complexity,
            context_size=context_size,
            ambiguity=ambiguity,
            error_consequence=error_consequence,
            speed_tolerance=speed_tolerance,
            data_sensitivity=data_sensitivity,
            cost_justification=cost_justification,
        )
        score = (
            breakdown.complexity * 5
            + breakdown.context_size * 3
            + breakdown.ambiguity * 3
            + breakdown.error_consequence * 2
            + breakdown.speed_tolerance * 2
            + breakdown.data_sensitivity * 3
            + breakdown.cost_justification * 2
        )
        recommended_model = self.model_id if score < 60 else "strong_model_required_by_policy"
        return QwenRoutingDecision(
            task_type=task_type,
            difficulty_score=score,
            score_breakdown=breakdown,
            recommended_model=recommended_model,
            reason="Dry-run deterministic routing. No Qwen network call was made.",
            requires_clarification=not bool(input_payload),
            clarification_questions=["What context should Imperium use?"] if not input_payload else [],
            requires_user_validation=task_type.startswith(("vault.", "imperium.", "weekly_report.")),
            risk_flags=["dry_run", "proposal_only_not_canonical"],
        )

    @staticmethod
    def _post_json(url: str, payload: dict[str, Any], timeout: int) -> dict[str, Any]:
        _validate_http_url(url)
        body = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
        request = urllib.request.Request(
            url,
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=timeout) as response:  # nosec B310
                raw = response.read().decode("utf-8")
        except urllib.error.URLError as exc:
            raise QwenProviderError("Qwen HTTP request failed.") from exc
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise QwenProviderError("Qwen HTTP response was not valid JSON.") from exc
        if not isinstance(parsed, dict):
            raise QwenProviderError("Qwen HTTP response JSON was not an object.")
        return parsed


def _validate_http_url(url: str) -> None:
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise QwenProviderError("Qwen provider URL must be an http(s) URL.")


def generate_wr_summary_with_qwen(
    *,
    session: ImperiumWeeklyReviewSession,
    input_payload: dict,
    qwen_client: QwenClient | None = None,
) -> QwenWeeklySummary:
    payload = {
        "session_id": str(session.id),
        "week_start": session.week_start.isoformat(),
        "week_end": session.week_end.isoformat(),
        **input_payload,
    }
    client = qwen_client or QwenClient()
    return client.generate_weekly_summary(input_payload=payload)
