"""Fixtures extracted from the n8n workflow JSON exports (ops/n8n/workflows/).

These are the exact payload shapes the three workflows validated and produced.
They feed the equivalence tests of the ported bridges (wr_bridge.py) and
replace workflow #3 (IMPERIUM_WR_INTERACTIVE_START_MOCK), whose only value was
contract testing — the JSON export is deleted from the repo (N8N_INVENTORY §A).
"""


def interactive_start_payload(*, task_id: str, session_id: str) -> dict:
    """Webhook input of IMPERIUM_WR_INTERACTIVE_START_QWEN_DRY_RUN."""
    return {
        "task_id": task_id,
        "session_id": session_id,
        "task_type": "weekly_report.interactive.start",
        "week_start": "2026-07-06",
        "week_end": "2026-07-12",
        "callback_url": f"/api/internal/ai/tasks/{task_id}/result",
        "wr_attach_url": f"/api/internal/weekly-review/{session_id}/attach-ai-result",
    }


def answers_integrate_payload(
    *, task_id: str, session_id: str, user_message_id: str, user_answer: str
) -> dict:
    """Webhook input of IMPERIUM_WR_ANSWERS_INTEGRATE_QWEN_DRY_RUN."""
    return {
        **interactive_start_payload(task_id=task_id, session_id=session_id),
        "task_type": "weekly_report.answers.integrate",
        "user_message_id": user_message_id,
        "user_answer": user_answer,
    }


# Expected callback body of workflow #1 (Build and Sign AI Result Callback node),
# minus the HMAC signing (no network hop in the ported flow) and minus model_used
# (resolved via the local_executor role since DV-6).
EXPECTED_START_CALLBACK_RESULT_TYPE = "weekly_report.summary"
EXPECTED_START_CALLBACK_SOURCE = "qwen_dry_run"
EXPECTED_START_CALLBACK_PROVIDER = "qwen-dry-run"
EXPECTED_START_RAW_WORKFLOW = "IMPERIUM_WR_INTERACTIVE_START_QWEN_DRY_RUN"
EXPECTED_START_IDEMPOTENCY_TEMPLATE = "wr_qwen_dry_run_result_{task_id}"
EXPECTED_START_ATTACH_TEMPLATE = "wr_qwen_dry_run_attach_{session_id}_{result_id}"

# Expected callback body of workflow #2 (Validate Payload and Sign Result Callback).
EXPECTED_ANSWERS_CALLBACK_RESULT_TYPE = "weekly_report.draft"
EXPECTED_ANSWERS_CALLBACK_TITLE = "Draft WR from dry-run answer integration"
EXPECTED_ANSWERS_CALLBACK_SUMMARY = (
    "Dry-run draft generated after integrating the latest WR answer."
)
EXPECTED_ANSWERS_CALLBACK_SOURCE = "qwen_dry_run_answers_integrate"
EXPECTED_ANSWERS_RAW_WORKFLOW = "IMPERIUM_WR_ANSWERS_INTEGRATE_QWEN_DRY_RUN"
EXPECTED_ANSWERS_ATTACH_TEMPLATE = "wr_answers_integrate_attach_{session_id}_{result_id}"


def mock_workflow_callback_body(*, week_start: str, week_end: str) -> dict:
    """The AIResultCallback body workflow #3 (MOCK) used to POST — now a fixture."""
    return {
        "result_type": "weekly_report.summary",
        "result_payload": {
            "summary": "Mock WR summary generated by n8n mock workflow.",
            "week_start": week_start,
            "week_end": week_end,
            "sections": [
                {
                    "title": "Résumé mock",
                    "content": (
                        "Ce résumé est généré uniquement pour tester le contrat "
                        "backend ↔ n8n."
                    ),
                }
            ],
            "questions": [
                "Quel a été le point le plus important de ta semaine ?",
                "Qu'est-ce qui t'a le plus freiné ?",
                "Quelle décision veux-tu prendre pour la semaine prochaine ?",
            ],
        },
        "model_used": "mock-n8n",
        "provider": "n8n-mock",
        "confidence": 0.8,
        "raw_payload": {
            "workflow": "IMPERIUM_WR_INTERACTIVE_START_MOCK",
            "source": "mock",
        },
    }
